# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bug',
            new_name='Feature',
        ),
    ]
